# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b60221248b693cefbbd7715116ad8b19aebc1447e77cf8d195c7c5a5d1080f30391f905f15228c115cfc2d48ff1a99c8c4c3ff95431f01b6f4243dc1cb305c48

test:
  secret_key_base: 9182fc4ab3879a611739016ddb3ca0efa1593b34c2ca0357bf19bdce0350d08511c7e0dc00f74fb2911ffc8fc07d13ea74fb47e1897495e5c7a4239d133f5c07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
